// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qasnlozbdoxldyszmqpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhc25sb3piZG94bGR5c3ptcXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODgxMjAsImV4cCI6MjA2Mzg2NDEyMH0.2sBu7LWOJ49FxK2xYqQ5QP_Kir__ucHPemmWw4eedlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);