// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tudyzsvraikekytpmkis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZHl6c3ZyYWlrZWt5dHBta2lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDA1MDUsImV4cCI6MjA2NDExNjUwNX0.M0UN6xNJkhXo2rd2891Bv_On9A-JTmMH1BEf2yqJoDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);