// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdzqwucgdevxkyypnywh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkenF3dWNnZGV2eGt5eXBueXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTQzOTAsImV4cCI6MjA2Mzc5MDM5MH0.PFG-IPRrBeqBSpfZawscKyN9iY1-fxsY4HpQbywAINw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);